[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[rpc_endpoints]
0g_testnet = "https://evmrpc-testnet.0g.ai"

[etherscan]
0g_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://chainscan-testnet.0g.ai/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
